export const CREATURE_NAMES = [
  "Molandak Bloom",
  "Chog Seedling",
  "Purple Hatch",
  "Block Sprite",
  "Gas Fern",
  "Moyaki Pod",
  "Nonce Bud",
  "Parallel Root",
  "Mint Wisp",
  "Trait Moss",
  "Monadling",
  "Rarity Beet",
  "Finality Dew",
  "Pixel Bract",
  "Holder Vine",
  "Floor Sprout",
  "Epoch Bulb",
  "Calldata Puff",
  "Archive Leaf",
  "Bloom Blob",
];

export const COLOR_PAIRS: Array<[string, string]> = [
  ["#f45fa5", "#91f36c"],
  ["#86d5ff", "#f3c45b"],
  ["#c184ff", "#61e3a5"],
  ["#ff7b54", "#f4df6a"],
  ["#69f0d8", "#a8ff60"],
  ["#ff8bd1", "#6bd3ff"],
];
